#pragma once

#define VER_PRODUCTBUILD 560
#define VER_PRODUCTVERSION_STR_W L"1.0.0.0"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"UNKNOWN BRANCH"
#define VER_NETWORK VER_PRODUCTBUILD
